"""add_stock_snapshots_and_update_items

Revision ID: 45042c69071d
Revises: 1c1965d89bf9
Create Date: 2026-05-20 21:46:42.879884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45042c69071d'
down_revision = '1c1965d89bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('stock_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('notes',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('snapshot_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('stock_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('notes',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('snapshot_at')

    with op.batch_alter_table('master_items', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
